name: Build and Push Docker Image
on:
  push:
    branches:
      - main
env:
  REGISTRY: emanzek
  IMAGE_NAME: demo-crud
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
